// === jwt.rs ======================================================================================
//
// Manages authenticating the JWTs generated by the authentication server.
//
// =================================================================================================

use serde::{self, Deserialize, Serialize};

use chrono::{self, Utc};

use mongodb::bson::{doc, oid::ObjectId};

// === JWTClaims ==================================================================================
//
// Stores the claims of the JWTs generated by the RestAPI's login service.
//
// Ensure that this struct stays in-sync with the claims generated by the RestAPI.
//
// ================================================================================================
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct JWTClaims {
    pub sub: String,

    // -- the time at which the token was issued, in UNIX epoch seconds
    #[serde(rename = "iat")]
    pub issued_at_epoch_secs: i64,

    // -- the time at which the token should expire, in UNIX epoch seconds
    #[serde(rename = "exp")]
    pub expiration_epoch_secs: i64,
} // -- end pub struct JWTClaims

#[derive(Clone, Debug)]
pub struct JWTExpiredError {
    expiration_dt_utc: Option<chrono::DateTime<Utc>>,
}

impl JWTExpiredError {
    pub fn new(timestamp: i64) -> Self {
        Self {
            expiration_dt_utc: chrono::DateTime::<Utc>::from_timestamp(timestamp, 0),
        }
    }
}

impl std::fmt::Display for JWTExpiredError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "jwt expired at {:?}", self.expiration_dt_utc)
    }
}

impl std::error::Error for JWTExpiredError {}

pub fn get_user_id_from_jwt(
    token_s: &str,
    secret: &str,
) -> Result<ObjectId, Box<dyn std::error::Error + Send + Sync>> {
    use hmac::{Hmac, Mac};
    use jwt::{Header, Token, VerifyWithKey};
    use sha2::Sha256;

    let key: Hmac<Sha256> = Hmac::new_from_slice(secret.as_bytes())?;
    let token: Token<Header, JWTClaims, _> = token_s.verify_with_key(&key)?;
    let claims = token.claims();

    let timestamp_now_utc = chrono::Local::now().to_utc().timestamp();
    let timestamp_exp_utc = claims.expiration_epoch_secs;

    if timestamp_now_utc >= timestamp_exp_utc {
        Err(Box::new(JWTExpiredError::new(timestamp_exp_utc)))
    } else {
        Ok(ObjectId::parse_str(claims.sub.as_str())?)
    }
}
