// === wss =========================================================================================
//
// Encapsulates functionality for the web socket server and its dependencies.
//
// Overview:
//  - server: Core logic of the web socket server
//  - protocol: Contains specifications of message protocols sent to and from the client.
//  - db: Interface for the MongoDB database
//  - jwt: Utilities for authenticating JWTs generated by the authentication server.
//  - models: Contains specifications of objects that users manipulate via the whiteboard editor.
//  - store: Contains specifications of traits for fetching objects from a form of storage.
//  - utils: Miscellaneous utility functions used by other submodules.
//
// =================================================================================================

pub mod server;
pub mod protocol;
pub mod db;
pub mod jwt;
pub mod models;
pub mod store;
pub mod collections;
pub mod utils;
