# -- Append the following to the end of your system smb.conf file.
# -- On Linux, this should be located at /etc/samba/smb.conf.
[boardly-docker-mailserver]
  comment = Persistent data for Boardly's docker mailserver
  # -- TODO: replace <PATH_TO_REPO> with the absolute path to the repository
  # directory.
  path = <PATH_TO_REPO>/.data/mailserver/
  read only = no
  browsable = yes
  # necessary for allowing symlinks, hard links, etc.
  smb3 unix extensions = yes
  ea support = yes
  posix locking = yes
  ntvfs handler = unixuid, ipc, posix
