apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31437
        hostPort: 8080
        protocol: TCP
      - containerPort: 30478
        hostPort: 8443
        protocol: TCP
      - containerPort: 80
        hostPort: ${WHITEBOARD_EDITOR_HTTP_PORT}
        protocol: TCP
      - containerPort: 443
        hostPort: ${WHITEBOARD_EDITOR_HTTPS_PORT}
        protocol: TCP
