apiVersion: v1
kind: ConfigMap
metadata:
  name: whiteboard-editor
data:
  # Database
  mongo_uri: "${WHITEBOARD_EDITOR_MONGO_URI}"

  # JWT
  jwt_secret: "${WHITEBOARD_EDITOR_JWT_SECRET}"
  jwt_expiration_secs: "${WHITEBOARD_EDITOR_JWT_EXPIRATION_SECS}"

  # Temp user settings
  temp_user_expiration_secs: "${WHITEBOARD_EDITOR_TEMP_USER_EXPIRATION_SECS}"
