apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: whiteboard-editor
spec:
  gatewayClassName: cloud-provider-kind
  listeners:
  - name: http
    hostname: "*.${WHITEBOARD_EDITOR_DOMAIN}"
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same
  - name: https
    hostname: "*.${WHITEBOARD_EDITOR_DOMAIN}"
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: Same
