apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whiteboard-editor-rest-api-route
  namespace: whiteboard-editor
spec:
  parentRefs:
  - name: gateway
    namespace: whiteboard-editor
  hostnames:
  - "*.${WHITEBOARD_EDITOR_DOMAIN}"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: rest-api-service
      namespace: whiteboard-editor
      port: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whiteboard-editor-web-socket-server-route
  namespace: whiteboard-editor
spec:
  parentRefs:
  - name: gateway
    namespace: whiteboard-editor
  hostnames:
  - "*.${WHITEBOARD_EDITOR_DOMAIN}"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /ws
    backendRefs:
    - name: web-socket-server-service
      namespace: whiteboard-editor
      port: 3000
