apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: whiteboard-editor-mailserver-smtp
  namespace: whiteboard-editor
spec:
  parentRefs:
    - name: gateway
      namespace: whiteboard-editor
      kind: Gateway
      sectionName: smtp
  rules:
    - name: smtp
      backendRefs:
        - name: mailserver-service
          namespace: whiteboard-editor
          port: 25
---
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: whiteboard-editor-mailserver-esmtp-implicit-tls
  namespace: whiteboard-editor
spec:
  parentRefs:
    - name: gateway
      namespace: whiteboard-editor
      kind: Gateway
      sectionName: esmtp-implicit-tls
  hostnames:
    - "mail.${WHITEBOARD_EDITOR_DOMAIN}"
  rules:
    - name: esmtp
      backendRefs:
        - name: mailserver-service
          namespace: whiteboard-editor
          port: 465
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: whiteboard-editor-mailserver-esmtp-explicit-tls
  namespace: whiteboard-editor
spec:
  parentRefs:
    - name: gateway
      namespace: whiteboard-editor
      kind: Gateway
      sectionName: esmtp-explicit-tls
  rules:
    - name: esmtp
      backendRefs:
        - name: mailserver-service
          namespace: whiteboard-editor
          port: 587
---
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
metadata:
  name: whiteboard-editor-mailserver-imaps
  namespace: whiteboard-editor
spec:
  parentRefs:
    - name: gateway
      namespace: whiteboard-editor
      kind: Gateway
      sectionName: imaps
  hostnames:
    - "mail.${WHITEBOARD_EDITOR_DOMAIN}"
  rules:
    - name: imaps
      backendRefs:
        - name: mailserver-service
          namespace: whiteboard-editor
          port: 993
