apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: data
  namespace: whiteboard-editor

spec:
  storageClassName: samba-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
