apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-editor-rest-api
  labels:
    app: whiteboard-editor.rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whiteboard-editor-rest-api
  template:
    metadata:
      labels:
        app: whiteboard-editor-rest-api
    spec:
      containers:
      - name: whiteboard-editor-rest-api
        image: ${WHITEBOARD_EDITOR_CR_URI}/rest_api:${WHITEBOARD_EDITOR_TAG}
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
        env:
          - name: MONGO_URI
            valueFrom:
              configMapKeyRef:
                name: whiteboard-editor
                key: mongo_uri
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: whiteboard-editor
                key: jwt_secret
          - name: JWT_EXPIRATION_SECS
            valueFrom:
              configMapKeyRef:
                name: whiteboard-editor
                key: jwt_expiration_secs
          - name: TEMP_USER_EXPIRATION_SECS
            valueFrom:
              configMapKeyRef:
                name: whiteboard-editor
                key: temp_user_expiration_secs
